### ISSUE TITLE
Iteration Plan for Feb 2018

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#66]
This plan captures our work in **February**. This is a 4 week iteration. **We will ship late February.**

## Plan Items ##

Below is a summary of the top level plan items. **This list is subject to change.**

### Bugs ###
- [x] Multiple Timepicker Functionality #43 @jasonbev
- [x] Mobile/Tablet Display Issue - Soft keyboard on Android covering field #50 @jasonbev
- [x] Report Icons aren't displaying on Print #51 @jasonbev
- [x] Non-Editable fields removed from view - Mobile #55 @jasonbev
- [x] Unable to link to page from Chart/Graph #58 @jasonbev
- [x] List box single select not bringing the Keyboard #64 @jaffars
- [x] DateTime field in mobile - no formatting #65 @jasonbev

### Features ###
- [x] Webservice: New Overridable Function #57 @paulfisher53
- [x] Sorting on Table Keys #69 @paulfisher53

### Docs and Test Cases ###
- [x] Global Functions
- [x] Application Module
- [x] AppObject Class

---

### Deferred ###
* Tablet view subpage scrolling is sticky and not consistent - Tablet #59 @jaffars

**Comment by paulfisher53** [comment]
No time for #59 , maybe we can add it to March iteration

**Comment by paulfisher53** [comment]
Shipped. Closed.
