### ISSUE TITLE
Iteration Plan for Mar 2018

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#73]
This plan captures our work in **March**. This is a 4 week iteration. **We will ship late March.**

## Plan Items ##

Below is a summary of the top level plan items. **This list is subject to change.**

### Bugs ###
- [x] Grid Control- Desktop Version fixes #34 @jaffars
- [x] Excess white space - Chartist Display cause #38 @jasonbev
- [x] Mobile Loader not displaying #52 @jasonbev
- [x] Mandatory Date fields - Grid #56 @jasonbev
- [x] Tablet View - design and usability issues due to orientation #62 @jaffars

### Features ###
- [x] Grand Totals - Report grouping #70 @jasonbev
- [x] Dashboard custom caption #75 @jasonbev

### Docs and Test Cases ###
- [x] CodeEngine Module
- [x] Record Class

---

### Deferred ###
- Tablet view subpage scrolling is sticky and not consistent #59 @jaffars
- DDSlick in tablet view display issue #60 @jaffars
- Mobile/Tablet View- Unable to type into anyvalue for search textbox #68 @jaffars

**Comment by paulfisher53** [comment]
#59 , #60 and #68 have been deferred to the next iteration

**Comment by paulfisher53** [comment]
Shipped. Closed.
