### ISSUE TITLE
Iteration Plan for Apr 2018

### ISSUE THREAD

**Issue by paulfisher53** [LiveappSolutions/Liveapp#83]
This plan captures our work in **April**. This is a 3 week iteration. **We will ship late April.**

## Plan Items ##

Below is a summary of the top level plan items. **This list is subject to change.**

### Bugs ###
- [x] Mobile/Tablet View- Unable to type into anyvalue for search textbox #68 @jaffars
- [x] Menu Items not referencing ClientCaption + ProgramCaption #76 @jasonbev
- [x] Xpress User Layout table performance #82 @paulfisher53

### Features ###
- [x] Tracking of device login #77 @jaffars
- [x] Card Form: Field Mask #81 @paulfisher53

### Docs and Test Cases ###
- [x] Table Options (Docs) #84 @paulfisher53
- [x] Page Options (Docs) #84 @paulfisher53
- [x] Field Options (Docs) #84 @paulfisher53
- [x] Column Options (Docs) #84 @paulfisher53

---

### Deferred ###

- Tablet view subpage scrolling is sticky and not consistent #59 @jaffars
- DDSlick in tablet view display issue #60 @jaffars

**Comment by paulfisher53** [comment]
Shipped. Closed.
